[project]
name = "zipapprobot"
version = "0.0.1"
description = ""
authors = [{name = "you", email = "you@example.com"}]
dependencies = ["robotframework>=6.1"]
requires-python = ">=3.11.0"
license = {text = "Apache License"}
