name: Python application

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: basic
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install git+https://github.com/franzhaas/robotframework.git@no_pythonpathsetter3
        pip install cx-Freeze
        cp $(which robot) robot
        python setup.py build
        cd examples/basic
        ../../build/*/robot_run . 
    - name: numpy
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install git+https://github.com/franzhaas/robotframework.git@no_pythonpathsetter3
        pip install cx_Freeze numpy pandas
        cp $(which robot) robot
        python setup2.py build
        cd examples/numpy
        ../../build/*/robot_run .
