name: frozen app using cx_freeze on ubuntu using setup.py
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: basic
      run: |
        cd cx_Freeze
        python -m venv venv
        source venv/bin/activate
        pip install robotframework cx_Freeze
        python setup_basic.py build || true
    - name: basic_run
      run: |
        ./cx_Freeze/build/*/robot_run_basic examples/basic/

    - name: numpy
      run: |
        cd cx_Freeze
        python3 -m venv venv
        source venv/bin/activate
        pip install robotframework cx_Freeze pandas numpy
        python setup_numpy.py build
    - name: numpy_run
      run: |
        ./cx_Freeze/build/*/robot_run_numpy examples/numpy/
