name: frozen app with cx_freeze on linux

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: basic
      run: |
        cd cx_Freeze_win
        uvx --from cx_Freeze --with numpy,pandas,robotframework cxfreeze build || true
        build/*/robot ../examples/
