name: Python application

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdm pdm-packer
        cd examples/basic
        pdm install
        pdm pack -m runway:main
        cd ../numpy
        pdm install
        pdm pack -m runway:main
        cd ..
        cd ..

    - name: Run tests
      run: |
        cd examples/basic
        python zipapprobot.pyz .
        cd ../numpy
        python zipapprobot.pyz .
        
