name: zipapp using pdm on ubuntu

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: |
        cd examples/basic
        uvx pdm install
        uvx --with pdm-packer pdm pack -m runway:main
        uvx --with pdm-packer pdm pack -o robotfileincluded.pyz -m runway:main_with_packaged_robot_file
        cd ../numpy
        uvx pdm install
        uvx --with pdm-packer pdm pack -m runway:main
        cd ..
        cd ..

    - name: Run tests
      run: |
        cd examples/basic
        python zipapprobot.pyz .
        python robotfileincluded.pyz
        cd ../numpy
        python zipapprobot.pyz .
        
