name: Python application

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [windows-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: basic
      run: |
        python -m venv venv
        venv/Scripts/activate
        pip install robotframework cx_Freeze
        cp venv/Lib/site-packages/robot/run.py robot
        python setup.py build
        dir build
        dir build\exe.win-amd64-3.12\
        cd examples/basic
        ../../build/*/robot_run . 
    - name: numpy
      run: |
        python -m venv venv
        venv/Scripts/activate
        pip install robotframework cx_Freeze numpy pandas
        where robot
        python setup2.py build
        cd examples/numpy
        ../../build/*/robot_run .
